name: Build and Deploy

on:
  pull_request:
  push:

jobs:
  typeset:
    name: Typeset
    runs-on: ubuntu-latest
    container: registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-09-08-medium
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: |
        tlmgr install moderncv graphics luatexja haranoaji fixme biber biblatex cjk
        tlmgr path add
    - uses: actions/cache@v4
      name: "Cache generated files"
      with:
        path: |
          svg-inkscape
          _minted-*
          *.aux
          *.fls
          *.out
          *.listing
          *.fdb_latexmk
          *.bbl
          *.blg
          *.bcf
          *.ltjruby
          *.run.xml
          *.toc
          *.synctex.gz
        key: "local-cache-${{hashFiles('**/*.tex', '**/*.sty', '**/*.svg', '**/*.bib')}}"
        restore-keys: |
          latex-cache-
    - name: Typeset Japanese CV
      run: |
        latexmk cv-ja.tex
    - name: Typeset English CV
      run: |
        latexmk cv-en.tex
    - name: Create Tarball
      run: |
        mkdir -p cvs/
        cp index.html cv-ja.pdf cv-en.pdf cvs/
        tar caf cvs.tar.gz cvs/
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        path: cvs.tar.gz

  deploy:
    needs: [typeset]
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref_name == 'master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v4
      - name: Extract CVs
        run: |
          ls -R
          tar xaf ./artifact/cvs.tar.gz
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './cvs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4