name: Build and Deploy

on:
  push:


jobs:
  typeset:
    name: Typeset
    runs-on: ubuntu-latest
    container: registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-09-08-full
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: "Cache generated files"
      with:
        path: |
          svg-inkscape
          _minted-*
          *.aux
          *.fls
          *.out
          *.listing
          *.fdb_latexmk
          *.bbl
          *.blg
          *.bcf
          *.ltjruby
        key: "local-cache-${{hashFiles('**/*.tex', '**/*.sty', '**/*.svg', '**/*.bib')}}"
        restore-keys: |
          latex-cache-
    - name: Typeset Japanese CV
      run: |
        latexmk cv-ja.tex
    - name: Typeset English CV
      run: |
        latexmk cv-en.tex
    - name: Create Tarball
      run: |
        mkdir -p cvs/
        mv cv-ja.pdf cv-en.pdf cvs/
        tar caf cvs.tar.gz cvs/
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        path: cvs.tar.gz

